server.port=${PORT:8080}
spring.application.name=recursos
spring.datasource.url=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:6543/postgres?user=postgres.shvgudeggtsmfywaixeg&password=z4n3b9HxngAWHpmR
spring.datasource.username=postgres.shvgudeggtsmfywaixeg
spring.datasource.password=z4n3b9HxngAWHpmR
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true